CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255)
);

CREATE TABLE tracks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    category VARCHAR(255),
    deadline DATE,
    created_at DATE,
    user_id BIGINT,
    CONSTRAINT fk_tracks_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    status VARCHAR(255),
    order_index INT,
    track_id BIGINT,
    CONSTRAINT fk_tasks_track FOREIGN KEY (track_id) REFERENCES tracks (id)
);